"""Per-field liveness/safety metadata for the Pilots API's settings editors.

Answers, for one ``Settings`` field, the question an operator actually has in
front of a settings form: **"if I change this and press Save, what happens?"**

Until this module existed the five ``/settings/*`` editors in
``api/pilots_api.py`` all answered that with one hardcoded, screen-wide string
— ``"applies": "next_daemon_restart"`` — which was a true statement about a
pure ``.env`` write and is no longer true now that ``runtime_flags`` can apply
a change to the running process. This module replaces the guess with the four
real answers, per field:

``immediately``
    A live change is observed. Every attributable read of this field is a
    *fresh* read (``docs/settings_liveness.json``'s ``live_safe`` bucket), so
    the write path may additionally push it onto the running process's own
    ``settings`` singleton via ``runtime_flags_writer.write_override``.

``next_daemon_restart``
    At least one read *captures* the value — an import-time constant, a
    constructor field, a decorator argument, an ``os.environ`` read. The
    ``.env`` write is durable but the running process keeps the old value.
    :func:`restart_reason` renders WHY, and :func:`capture_sites` names the
    exact ``file:line`` sites so the claim is checkable rather than trusted.

``no_effect``
    The field has zero production reads and its name never appears as a string
    literal in production code. Writing it does nothing, ever.

``env_pinned``
    A real shell export (``SOME_FIELD=x python3 main.py``) is live for this
    field right now. That always wins over both the runtime store and ``.env``,
    regardless of what the static classifier says — so this is a DOWNGRADE
    applied on top of the classification, never a classification of its own.

--------------------------------------------------------------------------
Fresh-per-request vs. cached
--------------------------------------------------------------------------
The two halves have genuinely different lifetimes and must not be conflated:

* The **classification** (``live_safe``/``restart_required``/``no_op``) is a
  static property of the source tree, committed to ``docs/settings_liveness.json``
  and regenerated by ``scripts/settings_liveness.py``. It cannot change while a
  process runs, so it is parsed once and cached (:func:`load_liveness`).
* **Env-pinning** and **store membership** are per-process, per-moment facts.
  An operator can create ``output/runtime_flags.json`` between two requests.
  :func:`env_pinned_keys` and :func:`runtime_store_keys` therefore delegate to
  ``runtime_flags`` on EVERY call and are deliberately not cached. Baking
  either into a static artifact would be exactly the kind of stale claim this
  module exists to eliminate.

--------------------------------------------------------------------------
Honesty rules this module follows
--------------------------------------------------------------------------
* **Never fabricates** (CONSTRAINT #4). ``capture_sites`` returns ``[]`` for a
  ``live_safe`` field because that is the measured answer — "the classifier
  found nothing capturing this" — and ``[]`` is deliberately distinguishable
  from the artifact being unreadable. ``restart_reason`` is ``None`` for any
  field that does not need a restart, never a filler string.
* **Never raises** (CONSTRAINT #6). A missing, corrupt, or wrong-shaped
  artifact degrades to :data:`CLASSIFICATION_UNKNOWN` with a WARNING.
* **An unknown classification reports — and behaves as —
  ``next_daemon_restart``.** This is not a guess dressed as a measurement. The
  SAME classification drives the write path: a field this module cannot
  classify is never live-applied, so "your change takes effect at the next
  restart" is true *by construction* rather than by assumption. It also matches
  the direction ``scripts/settings_liveness.py`` itself fails in ("it prefers a
  false ``restart_required`` over a false ``live_safe``"). ``restart_reason``
  says plainly that the artifact was unreadable instead of inventing a site.

--------------------------------------------------------------------------
Module constraints
--------------------------------------------------------------------------
* Dependency-light read helper on the API path: stdlib + ``runtime_flags`` +
  ``settings_keysets`` only. It never imports ``settings``, and never imports
  any heavy calculation engine (``pilots/`` modules are AST-guarded against
  those — see ``tests/test_pilots_forecast_skill.py``).
* **Contains no ``Settings`` field-name string literals, deliberately.**
  ``scripts/settings_liveness.py`` scans production files for exact field-name
  literals to decide whether a field with no attributable read is genuinely
  ``no_op`` or is reached through a name-driven dispatcher. A prose table keyed
  by field name in here would register as a phantom read site for every field
  it named and corrupt the very artifact this module consumes. Everything below
  is keyed by CLASSIFIER RULE name instead.
* Path anchoring: the artifact is located from THIS FILE, never from the
  process CWD (same rule as ``runtime_flags.DEFAULT_STORE_PATH`` — a real bug in
  this repo once had an upward path search escape a git worktree).
"""

from __future__ import annotations

import importlib.util
import json
import logging
import threading
from pathlib import Path
from typing import Any, Dict, FrozenSet, List, Optional

import runtime_flags
from settings_keysets import DANGEROUS_KEYS

logger = logging.getLogger(__name__)

__all__ = [
    "APPLIES_IMMEDIATELY",
    "APPLIES_NEXT_RESTART",
    "APPLIES_NO_EFFECT",
    "APPLIES_ENV_PINNED",
    "APPLIES_STATES",
    "SOURCE_RUNTIME_STORE",
    "SOURCE_ENV_FILE",
    "CLASSIFICATION_UNKNOWN",
    "LIVENESS_ARTIFACT_PATH",
    "load_liveness",
    "reset_cache",
    "classification",
    "capture_sites",
    "restart_reason",
    "is_dangerous",
    "env_pinned_keys",
    "runtime_store_keys",
    "live_apply_available",
    "applies_for",
    "field_metadata",
    "summarize_applies",
]

#: Module that performs the actual live apply onto the running ``settings``
#: singleton. Named as a string rather than imported, because this module must
#: keep working (reporting honestly) in a checkout where it does not exist.
WRITER_MODULE = "runtime_flags_writer"

#: Anchored to THIS FILE (``<repo root>/pilots/settings_meta.py``), so the
#: artifact resolves the same from any CWD and never escapes the worktree.
LIVENESS_ARTIFACT_PATH = Path(__file__).resolve().parent.parent / "docs" / "settings_liveness.json"

# ---- the four `applies` states (the wire contract) -------------------------
APPLIES_IMMEDIATELY = "immediately"
APPLIES_NEXT_RESTART = "next_daemon_restart"
APPLIES_NO_EFFECT = "no_effect"
APPLIES_ENV_PINNED = "env_pinned"

#: Order matters: it is the order the counts are reported in, most-live first.
APPLIES_STATES = (
    APPLIES_IMMEDIATELY,
    APPLIES_NEXT_RESTART,
    APPLIES_NO_EFFECT,
    APPLIES_ENV_PINNED,
)

# ---- where the CURRENTLY ACTIVE value came from ----------------------------
#: An override for this field is present in ``output/runtime_flags.json``.
SOURCE_RUNTIME_STORE = "runtime_store"
#: No override — the value is ordinary ``.env`` / real-env / field-default
#: resolution. (Which of those three is not distinguished: pydantic-settings
#: does not report its own winning source, and guessing would be fabrication.)
SOURCE_ENV_FILE = "env_file"

#: Returned by :func:`classification` when the artifact could not be read or
#: does not mention the field. See the module docstring for why this maps to
#: ``next_daemon_restart`` rather than to a fifth wire state.
CLASSIFICATION_UNKNOWN = "unknown"

_CLASSIFICATION_TO_APPLIES: Dict[str, str] = {
    "live_safe": APPLIES_IMMEDIATELY,
    "restart_required": APPLIES_NEXT_RESTART,
    "no_op": APPLIES_NO_EFFECT,
    CLASSIFICATION_UNKNOWN: APPLIES_NEXT_RESTART,
}

# ---------------------------------------------------------------------------
# Rule -> operator-readable prose
# ---------------------------------------------------------------------------
# Keyed by ``scripts/settings_liveness.py``'s own rule names (the strings it
# writes into each capture site's ``rules`` list). Every phrase completes the
# sentence "This value ...", is written for an operator rather than for someone
# who has read the classifier, and states the OBSERVABLE consequence rather
# than the AST pattern that detected it.
_RULE_PROSE: Dict[str, str] = {
    "module_level": "was read once, when its module was first imported",
    "class_body": "was read once in a class body, when its module was first imported",
    "decorator_arg": "was baked into a decorator when its module was first imported",
    "default_arg": "was baked into a function's default argument at import time",
    "frozen_dataclass_default": "was frozen into a dataclass default at import time",
    "init_self_assign": "was copied into an object when that object was constructed",
    "init_body": "was read while an object was being constructed",
    "cross_module_init_helper": "was read by a helper called while an object was being constructed",
    "indirect_init_helper_d1": "was read one call away from an object's constructor",
    "indirect_init_helper_d2": "was read two calls away from an object's constructor",
    "indirect_init_helper_d3": "was read three calls away from an object's constructor",
    "method_self_assign": (
        "was cached onto a live object by a method, and only refreshes when that "
        "method runs again"
    ),
    "memoized_singleton": "is memoized — the first call's result is cached for the whole process",
    "global_assign": "was assigned into a module-level global",
    "closure_value": "was captured inside a closure",
    "os_environ": (
        "is read straight from the process environment, which a settings change "
        "cannot reach"
    ),
    "dynamic_name_literal_unattributable": (
        "is only reached through a name-driven lookup, so a fresh re-read could "
        "not be proven"
    ),
    "dynamic_in_capture_context": (
        "is read through a dynamic lookup inside code that captures its value"
    ),
}

#: How many capture sites to name in ``restart_reason`` before summarising the
#: rest as a count. ``capture_sites`` always returns the full list — this only
#: bounds the human-readable sentence.
_MAX_SITES_IN_REASON = 2

# ---------------------------------------------------------------------------
# Artifact loading (cached — the classification is a static property)
# ---------------------------------------------------------------------------
_cache_lock = threading.Lock()
_cache: Optional[Dict[str, Any]] = None


def reset_cache() -> None:
    """Drop the parsed-artifact cache. For tests, and for an operator who has
    just regenerated ``docs/settings_liveness.json`` in a long-lived daemon."""
    global _cache
    with _cache_lock:
        _cache = None


def load_liveness(*, path: Optional[Any] = None) -> Dict[str, Any]:
    """Parse and shape-check ``docs/settings_liveness.json``.

    Returns a normalised ``{"live_safe": set, "restart_required": dict,
    "no_op": set}``. Never raises: a missing/corrupt/wrong-shaped artifact
    degrades to empty buckets, which makes every field
    :data:`CLASSIFICATION_UNKNOWN` (CONSTRAINT #6).

    Cached, since the artifact cannot change while a process runs. Passing an
    explicit ``path`` bypasses the cache entirely (tests).
    """
    if path is not None:
        return _parse(Path(path))

    global _cache
    with _cache_lock:
        if _cache is None:
            _cache = _parse(LIVENESS_ARTIFACT_PATH)
        return _cache


def _empty() -> Dict[str, Any]:
    return {"live_safe": frozenset(), "restart_required": {}, "no_op": frozenset(), "loaded": False}


def _parse(path: Path) -> Dict[str, Any]:
    """Read one artifact file into normalised buckets. Never raises."""
    try:
        raw = json.loads(path.read_text(encoding="utf-8"))
    except FileNotFoundError:
        logger.warning(
            "settings_meta: %s not found — every settings field will report "
            "'%s' with no capture sites. Regenerate with "
            "`python3 scripts/settings_liveness.py --write`.",
            path,
            APPLIES_NEXT_RESTART,
        )
        return _empty()
    except Exception as exc:  # noqa: BLE001 - dead-letter, never break a GET
        logger.warning(
            "settings_meta: could not parse %s (%s) — every settings field will "
            "report '%s' with no capture sites.",
            path,
            type(exc).__name__,
            APPLIES_NEXT_RESTART,
        )
        return _empty()

    if not isinstance(raw, dict):
        logger.warning("settings_meta: %s top level must be a JSON object.", path)
        return _empty()

    # `live_safe`/`no_op` are lists; `restart_required` is a dict of
    # field -> [site, ...]. Each is shape-checked independently so one broken
    # bucket does not discard the other two (dead-letter-per-bucket).
    live_safe = raw.get("live_safe")
    no_op = raw.get("no_op")
    restart = raw.get("restart_required")
    return {
        "live_safe": frozenset(x for x in live_safe if isinstance(x, str)) if isinstance(live_safe, list) else frozenset(),
        "no_op": frozenset(x for x in no_op if isinstance(x, str)) if isinstance(no_op, list) else frozenset(),
        "restart_required": {k: v for k, v in restart.items() if isinstance(k, str)} if isinstance(restart, dict) else {},
        "loaded": True,
    }


# ---------------------------------------------------------------------------
# Per-field queries
# ---------------------------------------------------------------------------
def classification(key: str, *, data: Optional[Dict[str, Any]] = None) -> str:
    """``"live_safe"`` / ``"restart_required"`` / ``"no_op"`` /
    :data:`CLASSIFICATION_UNKNOWN` for one field name."""
    d = data if data is not None else load_liveness()
    if key in d["restart_required"]:
        return "restart_required"
    if key in d["live_safe"]:
        return "live_safe"
    if key in d["no_op"]:
        return "no_op"
    return CLASSIFICATION_UNKNOWN


def capture_sites(key: str, *, data: Optional[Dict[str, Any]] = None) -> List[str]:
    """Every ``file:line`` the classifier found capturing this field's value.

    ``[]`` for a ``live_safe`` field is the measured answer — the classifier
    looked and found nothing capturing it — NOT "we did not check"
    (CONSTRAINT #4). The list is exposed so an operator can verify the
    ``next_daemon_restart`` claim themselves instead of taking it on faith.
    """
    d = data if data is not None else load_liveness()
    sites = d["restart_required"].get(key)
    if not isinstance(sites, list):
        return []
    out: List[str] = []
    for entry in sites:
        if isinstance(entry, dict):
            site = entry.get("site")
            if isinstance(site, str) and site not in out:
                out.append(site)
    return out


def _site_rule(entry: Any) -> Optional[str]:
    """The first rule on a site that this module has prose for."""
    if not isinstance(entry, dict):
        return None
    rules = entry.get("rules")
    if not isinstance(rules, list):
        return None
    for rule in rules:
        if isinstance(rule, str) and rule in _RULE_PROSE:
            return rule
    return None


def restart_reason(key: str, *, data: Optional[Dict[str, Any]] = None) -> Optional[str]:
    """A short, operator-readable sentence explaining WHY a field needs a
    restart — or ``None`` for a field that does not.

    Rendered from the classifier's structured capture-site data, never a raw
    dump of its internal rule names. ``None`` (not a filler string) whenever
    ``applies`` is ``immediately`` or ``no_effect``.
    """
    d = data if data is not None else load_liveness()
    cls = classification(key, data=d)
    if cls in ("live_safe", "no_op"):
        return None
    if cls == CLASSIFICATION_UNKNOWN:
        # Honest about the gap rather than inventing a capture site. These are
        # two different situations and must not share one message: a genuinely
        # unreadable artifact (`loaded: False`) vs. one that parsed fine but
        # simply has never mentioned this field (`loaded: True` — e.g. a field
        # added to an editor since the last `--write` run). Claiming "could not
        # be read" in the second case is itself false — every other field on
        # the same request classified correctly from the same data — and sends
        # an operator debugging JSON parsing instead of regenerating the
        # artifact.
        if not d.get("loaded"):
            return (
                "The settings-liveness report could not be read, so this "
                "field's behaviour could not be verified — it is treated as "
                "needing a restart, and is not applied to the running "
                "process."
            )
        return (
            "This field is not listed in the settings-liveness report "
            "(docs/settings_liveness.json may be out of date — regenerate "
            "with `python3 scripts/settings_liveness.py --write`), so its "
            "behaviour could not be verified — it is treated as needing a "
            "restart, and is not applied to the running process."
        )

    sites = d["restart_required"].get(key) or []
    named: List[str] = []
    for entry in sites:
        rule = _site_rule(entry)
        site = entry.get("site") if isinstance(entry, dict) else None
        if rule is None or not isinstance(site, str):
            continue
        named.append(f"{_RULE_PROSE[rule]} ({site})")
        if len(named) >= _MAX_SITES_IN_REASON:
            break

    total = len(capture_sites(key, data=d))
    if not named:
        # A restart_required field whose sites carry only rules this module has
        # no prose for. Say that plainly rather than guessing at a reason.
        if total:
            return (
                f"The running process captured this value at {total} "
                f"site{'s' if total != 1 else ''}; restart to pick up a change."
            )
        return "The running process captured this value; restart to pick up a change."

    reason = "This value " + "; and ".join(named) + "."
    remaining = total - len(named)
    if remaining > 0:
        reason += f" ({remaining} further capture site{'s' if remaining != 1 else ''}.)"
    return reason


def is_dangerous(key: str) -> bool:
    """Whether writing this field requires an explicit operator confirmation
    (``settings_keysets.DANGEROUS_KEYS``)."""
    return key in DANGEROUS_KEYS


# ---------------------------------------------------------------------------
# Per-request facts (never cached — see the module docstring)
# ---------------------------------------------------------------------------
def env_pinned_keys() -> FrozenSet[str]:
    """Upper-cased field names pinned by a REAL shell export right now.

    Delegates to ``runtime_flags.real_environment_keys()`` on every call — this
    changes per process and can change between two requests, so it must never
    be cached or precomputed into a static artifact. Degrades to ``frozenset()``
    (nothing pinned) rather than raising.
    """
    try:
        return runtime_flags.real_environment_keys()
    except Exception as exc:  # noqa: BLE001 - dead-letter (CONSTRAINT #6)
        logger.warning(
            "settings_meta: could not determine env-pinned keys (%s); reporting "
            "none as pinned.",
            type(exc).__name__,
        )
        return frozenset()


def runtime_store_keys() -> FrozenSet[str]:
    """Field names that currently have an override in ``output/runtime_flags.json``.

    Read fresh per call for the same reason as :func:`env_pinned_keys` — the
    store file can appear or change between requests. Never raises: a file-level
    problem degrades to "no overrides", and ``runtime_flags.load_store`` has
    already logged it.
    """
    try:
        flags, error = runtime_flags.load_store()
        if error is not None:
            return frozenset()
        return frozenset(flags)
    except Exception as exc:  # noqa: BLE001 - dead-letter (CONSTRAINT #6)
        logger.warning(
            "settings_meta: could not read the runtime override store (%s); "
            "reporting no overrides.",
            type(exc).__name__,
        )
        return frozenset()


def live_apply_available() -> bool:
    """Whether this process can actually push a value onto the running
    ``settings`` singleton right now.

    ``live_safe`` is a statement about the SOURCE TREE — "no read of this field
    captures its value" — and on its own it does NOT mean a change will be
    observed. That additionally requires a writer to exist and be importable.
    :data:`WRITER_MODULE` is a separate, newer module that is legitimately
    absent from some checkouts; where it is absent, a save writes ``.env`` and
    nothing else, so the running process keeps the old value and the honest
    answer for EVERY field is ``next_daemon_restart``.

    Reporting ``immediately`` on the strength of the classification alone would
    reintroduce, per field, exactly the kind of unchecked blanket claim this
    module exists to remove — so the two conditions are ANDed rather than the
    static half being trusted by itself.

    Uses ``find_spec`` rather than a real import: this is called on a read path
    and must not execute a module as a side effect of answering a GET. Never
    raises (CONSTRAINT #6) — any failure reports ``False``, the conservative
    direction.
    """
    try:
        return importlib.util.find_spec(WRITER_MODULE) is not None
    except Exception:  # noqa: BLE001 - dead-letter (CONSTRAINT #6)
        return False


#: Reason reported for a ``live_safe`` field in a checkout with no writer. Not a
#: capture site — the value is not captured anywhere; the live-apply path simply
#: does not exist here — so it is phrased as the different fact it is.
_NO_WRITER_REASON = (
    "Nothing in the running process holds onto this value, but this build has "
    "no way to push a change into the live process, so the new value is saved "
    "to .env and picked up on the next restart."
)


# ---------------------------------------------------------------------------
# Assembly
# ---------------------------------------------------------------------------
def applies_for(
    key: str,
    *,
    pinned: FrozenSet[str],
    data: Optional[Dict[str, Any]] = None,
    live_apply: bool = True,
) -> str:
    """The field's ``applies`` state.

    Derived from the static classification, then adjusted by two facts the
    classification cannot know, in this order:

    1. A real shell export live for this name downgrades to
       :data:`APPLIES_ENV_PINNED` — it wins over both the runtime store and
       ``.env`` regardless of what the classifier says, so it is checked first.
    2. ``live_apply=False`` (no writer in this checkout — see
       :func:`live_apply_available`) downgrades ``immediately`` to
       ``next_daemon_restart``. ``no_effect`` is untouched: a field nothing
       reads still does nothing whether or not a writer exists.
    """
    if key.upper() in pinned:
        return APPLIES_ENV_PINNED
    applies = _CLASSIFICATION_TO_APPLIES[classification(key, data=data)]
    if applies == APPLIES_IMMEDIATELY and not live_apply:
        return APPLIES_NEXT_RESTART
    return applies


def field_metadata(
    key: str,
    *,
    pinned: FrozenSet[str],
    stored: FrozenSet[str],
    data: Optional[Dict[str, Any]] = None,
    live_apply: bool = True,
) -> Dict[str, Any]:
    """The ``liveness`` sub-object attached to one field in a ``GET /settings/*``
    payload.

    ``pinned`` / ``stored`` / ``live_apply`` are passed in rather than looked up
    here so ONE request computes each once for all ~49 of its fields — but they
    are still computed fresh for that request (see :func:`env_pinned_keys`).
    """
    d = data if data is not None else load_liveness()
    is_pinned = key.upper() in pinned
    applies = applies_for(key, pinned=pinned, data=d, live_apply=live_apply)
    # A restart reason is about the CLASSIFICATION, so it is still reported for
    # an env-pinned field: the pin is the immediate blocker, but the capture
    # site is still true and still relevant once the pin is removed.
    reason = restart_reason(key, data=d)
    if (
        reason is None
        and applies == APPLIES_NEXT_RESTART
        and classification(key, data=d) == "live_safe"
    ):
        # Live-safe, but this build cannot apply it live. Say which of the two
        # it is rather than leaving a restart claim with no explanation.
        reason = _NO_WRITER_REASON
    return {
        "applies": applies,
        "restart_reason": reason,
        "capture_sites": capture_sites(key, data=d),
        "env_pinned": is_pinned,
        "dangerous": is_dangerous(key),
        # Raw membership in ``stored`` is NOT enough: a pin always wins over
        # the store (see applies_for's own ordering, checked first there for
        # the same reason), so a key that is BOTH stored and pinned is
        # currently active from the real shell export, not the store --
        # reporting "runtime_store" for it would contradict this same
        # payload's own "env_pinned": true one line up. A store entry can
        # also be a stale/invalid leftover the last apply skipped (e.g. a
        # field whose bounds changed after it was written, or the file
        # edited by hand) -- ``bootstrap`` keys are refused by the writer so
        # they can never legitimately reach the store at all. Neither of
        # those is applied either, so neither may claim this source.
        "source": (
            SOURCE_RUNTIME_STORE if (key in stored and not is_pinned) else SOURCE_ENV_FILE
        ),
    }


def summarize_applies(states: List[str]) -> Dict[str, Any]:
    """Roll a screen's per-field ``applies`` states into one honest summary.

    Returns ``{"applies": <summary>, "applies_counts": {state: n, ...}}``.
    The summary is the single shared state when every field agrees, ``"mixed"``
    when they do not, and — for a screen with no fields at all — ``"mixed"``
    would be a claim about nothing, so an empty screen reports
    ``next_daemon_restart`` (the conservative direction, matching the rest of
    this module).
    """
    counts = {state: 0 for state in APPLIES_STATES}
    for state in states:
        if state in counts:
            counts[state] += 1
    distinct = {s for s, n in counts.items() if n}
    if len(distinct) == 1:
        summary = next(iter(distinct))
    elif not distinct:
        summary = APPLIES_NEXT_RESTART
    else:
        summary = "mixed"
    return {"applies": summary, "applies_counts": counts}
