#!/usr/bin/env bash
# build_webapp_prod.sh — one-time/on-demand production build of the Pilots
# PWA for the Caddy + Tailscale deployment (see docs/RUNBOOK.md §0.2).
#
# Not run automatically by investyo_stack_service.sh (mirrors how .venv is
# built once by setup.sh, not rebuilt on every service start) -- re-run this
# manually whenever webapp/ source changes and you want the Tailscale-served
# build refreshed.
#
# GUARANTEES A WORKING BUILD, NOT JUST A COMPILING ONE. `npm run build` alone
# defaults to VITE_USE_MOCK=true (fabricated data -- see webapp/src/config/env.ts's
# parseUseMock: "Falls back to true (mock)" whenever the key is unset) and
# localhost-only base URLs, neither of which works for a build served to a
# phone over Tailscale (see webapp/.env.example and scripts/Caddyfile's own
# routing comments). This script refuses to silently ship that:
#   - if webapp/.env.production.local is missing, it's generated here from
#     `tailscale status` (fails loudly, with a clear fix, if tailscale isn't
#     signed in rather than falling back to something broken);
#   - if it already exists (e.g. hand-edited), it's left alone, but the build
#     still refuses to proceed unless VITE_USE_MOCK is EXPLICITLY set to a
#     false-spelling in it -- a present-but-wrong value and an absent key are
#     the same failure mode (both mean "mock"), so both are rejected the same
#     way.
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
WEBAPP_DIR="$REPO_ROOT/webapp"
ENV_FILE="$WEBAPP_DIR/.env.production.local"

cd "$WEBAPP_DIR"

if [ ! -f "$ENV_FILE" ]; then
    echo "$(date '+%F %T')  $ENV_FILE not found -- generating it from 'tailscale status' (see docs/RUNBOOK.md §0.2)."

    if ! command -v tailscale >/dev/null 2>&1; then
        echo "FATAL: tailscale is not installed. Install it (brew install tailscale), sign in" >&2
        echo "('sudo tailscale up'), then re-run this script -- or hand-write $ENV_FILE" >&2
        echo "yourself (see webapp/.env.example for every key) and re-run." >&2
        exit 1
    fi

    TAILNET_HOST="$(tailscale status --json 2>/dev/null | python3 -c '
import json, sys
try:
    data = json.load(sys.stdin)
    print(data.get("Self", {}).get("DNSName", "").rstrip("."))
except Exception:
    pass
' || true)"

    if [ -z "$TAILNET_HOST" ]; then
        echo "FATAL: could not determine this machine's Tailscale MagicDNS name." >&2
        echo "Run 'sudo tailscale up' and confirm 'tailscale status' shows a connected device," >&2
        echo "then re-run this script -- or hand-write $ENV_FILE yourself (see" >&2
        echo "webapp/.env.example) if you'd rather not depend on auto-detection." >&2
        exit 1
    fi

    cat > "$ENV_FILE" <<EOF
# Auto-generated by scripts/build_webapp_prod.sh on $(date '+%F %T') from
# 'tailscale status'. Safe to hand-edit -- this script will NOT overwrite an
# existing file, only generate one that's missing. Delete this file to force
# regeneration against the current Tailscale hostname.
#
# All four origins point at the same Caddy-fronted Tailscale endpoint --
# scripts/Caddyfile collapses all four backend ports plus the static build
# into one HTTPS origin published via 'tailscale serve'. /svc is the
# pilots_api-only proxy prefix Caddy strips before forwarding; see
# scripts/Caddyfile's own routing comments before changing any of these.
VITE_USE_MOCK=false
VITE_API_BASE_URL=https://${TAILNET_HOST}/svc
VITE_DATA_API_BASE_URL=https://${TAILNET_HOST}
VITE_METRICS_API_BASE_URL=https://${TAILNET_HOST}
VITE_CONTROL_API_BASE_URL=https://${TAILNET_HOST}

# MUST stay blank: this build is served to non-loopback devices (your phone),
# and VITE_API_TOKEN bakes into the JS bundle in plaintext if set. TokenGate
# (webapp/src/components/TokenGate.tsx) prompts for the real token once per
# browser and keeps it only in sessionStorage -- see webapp/src/auth/apiToken.ts.
VITE_API_TOKEN=
EOF
    echo "$(date '+%F %T')  Wrote $ENV_FILE (tailnet host: ${TAILNET_HOST})."
else
    echo "$(date '+%F %T')  Using existing $ENV_FILE."
fi

# Belt-and-suspenders even for a pre-existing file: refuse to ship a build
# that would silently fabricate data. A present-but-wrong value (VITE_USE_MOCK
# left at the .env.example default of "true", or any other truthy spelling)
# and an absent key are the same failure mode client-side, so both fail here.
if ! grep -qiE '^VITE_USE_MOCK=[[:space:]]*(false|0|no|off)[[:space:]]*$' "$ENV_FILE"; then
    echo "FATAL: $ENV_FILE does not explicitly set VITE_USE_MOCK to false/0/no/off." >&2
    echo "Without that, this 'production' build would fabricate mock data instead of" >&2
    echo "using your live backend -- see webapp/src/config/env.ts's parseUseMock." >&2
    echo "Add 'VITE_USE_MOCK=false' to $ENV_FILE (or delete it to regenerate from" >&2
    echo "'tailscale status') and re-run." >&2
    exit 1
fi

echo "$(date '+%F %T')  Installing webapp dependencies (npm ci)..."
npm ci

echo "$(date '+%F %T')  Building production webapp bundle..."
npm run build

echo "$(date '+%F %T')  Production build complete -> $WEBAPP_DIR/dist"
