#compdef python python3
# investyo command completion (zsh) — GENERATED by
# scripts/generate_shell_completion.py from cli_introspect/command_manifest.json.
# Do not edit by hand; re-run the generator. Enable with:  source completions/investyo.zsh
_investyo_complete() {
  local cur w i cmd="" sub="" ctx kind=""
  local -a cands disp
  cur="${words[CURRENT]}"
  for (( i=2; i < CURRENT; i++ )); do
    w="${words[i]}"
    if [[ -z "$cmd" ]]; then
      local prevw="${words[i-1]}"
      case "$w" in
        main.py|*/main.py) cmd='main.py' ;;
        main_orchestrator.py|*/main_orchestrator.py) cmd='main_orchestrator.py' ;;
        universe_engine.py|*/universe_engine.py) cmd='universe_engine.py' ;;
        app_shell.py|*/app_shell.py) cmd='app_shell.py' ;;
        execution.kill_switch) [[ "$prevw" == "-m" ]] && cmd='execution.kill_switch' ;;
        validation.harness) [[ "$prevw" == "-m" ]] && cmd='validation.harness' ;;
        prompt_registry) [[ "$prevw" == "-m" ]] && cmd='prompt_registry' ;;
        preflight_check.py|*/preflight_check.py) cmd='preflight_check.py' ;;
        refresh_validations.py|*/refresh_validations.py) cmd='refresh_validations.py' ;;
        daily_briefing.py|*/daily_briefing.py) cmd='daily_briefing.py' ;;
        track_record_status.py|*/track_record_status.py) cmd='track_record_status.py' ;;
      esac
    else
      case "$cmd" in
        prompt_registry)
          if [[ -z "$sub" ]]; then
            case "$w" in
            list) sub='list' ;;
            get) sub='get' ;;
            sync) sub='sync' ;;
            pin) sub='pin' ;;
            rollback) sub='rollback' ;;
            diff) sub='diff' ;;
            verify) sub='verify' ;;
            publish) sub='publish' ;;
            esac
          fi
          ;;
      esac
    fi
  done

  if [[ -z "$cmd" ]]; then
    _files
    return
  fi

  ctx="$cmd"; [[ -n "$sub" ]] && ctx="$cmd/$sub"
  case "$ctx" in
    main.py) kind='opts'; cands=(--interval --refresh-account --agent); disp=('--interval  -- Refresh market data every N seconds (0 = run once and exit).' '--refresh-account  -- Force a fresh Robinhood fetch on this launch (bypasses daily cache).' '--agent  -- Run the autonomous advisory agent loop: adaptive cadence based on market hours / VIX / regime, backlog reminders for high-conviction signals the operator has not yet logged a decision for, persistent state across restarts.  Takes precedence over --interval.') ;;
    main_orchestrator.py) kind='opts'; cands=(--dry-run --strict); disp=('--dry-run  -- Log intended orders but do not submit to broker.' '--strict  -- Treat DashboardSchema validation failures as fatal (exit 1). For CI / schema-drift gating.') ;;
    universe_engine.py) kind='opts'; cands=(--date --report); disp=('--date  -- As-of date in YYYY-MM-DD format' '--report  -- Print survivorship bias report') ;;
    app_shell.py) kind='opts'; cands=(--interval); disp=('--interval  -- Advisory engine refresh cadence in seconds (default: 300).') ;;
    execution.kill_switch) kind='opts'; cands=(--activate --deactivate --status --reason); disp=('--activate  -- Activate the kill switch.' '--deactivate  -- Deactivate the kill switch.' '--status  -- Print current status.' '--reason  -- Reason text (--activate only).') ;;
    validation.harness) kind='opts'; cands=(--strategy --start --end); disp=('--strategy  -- Name of the strategy to validate' '--start  -- Start date (YYYY-MM-DD)' '--end  -- End date (YYYY-MM-DD)') ;;
    prompt_registry) kind='subs'; cands=(list get sync pin rollback diff verify publish); disp=('list  -- Table of prompt IDs with pinned / remote-latest / newest-cached versions.' 'get  -- Print a resolved prompt body.' 'sync  -- Fetch the remote manifest and pre-warm the disk cache.' 'pin  -- Pin a prompt ID to a specific version.' 'rollback  -- Roll back to the previous cached version.' 'diff  -- Unified diff between two versions of a prompt.' 'verify  -- Re-check signatures and guardrails for cached versions.' 'publish  -- Sign a file and push it to the remote store (publish credentials required).') ;;
    prompt_registry/list) kind='opts'; cands=(); disp=() ;;
    prompt_registry/get) kind='opts'; cands=(--version -v --raw); disp=('--version  -- Specific version (e.g. 1.0.0 or '\''baseline'\''). Default: full resolution chain.' '-v  -- Specific version (e.g. 1.0.0 or '\''baseline'\''). Default: full resolution chain.' '--raw  -- Suppress the header comment line — print body text only.') ;;
    prompt_registry/sync) kind='opts'; cands=(); disp=() ;;
    prompt_registry/pin) kind='opts'; cands=(); disp=() ;;
    prompt_registry/rollback) kind='opts'; cands=(); disp=() ;;
    prompt_registry/diff) kind='opts'; cands=(); disp=() ;;
    prompt_registry/verify) kind='opts'; cands=(); disp=() ;;
    prompt_registry/publish) kind='opts'; cands=(--version -v --author --notes); disp=('--version  -- Version string to publish (e.g. 1.1.0).' '-v  -- Version string to publish (e.g. 1.1.0).' '--author  -- Author identifier.' '--notes  -- Changelog note.') ;;
    preflight_check.py) kind='opts'; cands=(--json --skip --fire-alerts); disp=('--json  -- Output machine-readable JSON array instead of a human-readable table' '--skip  -- Skip named checks (e.g. --skip heartbeat_fresh paper_trading_duration). Useful in CI where certain checks are contextually inapplicable.' '--fire-alerts  -- Dispatch a CRITICAL alert via observability.alerts.send_alert when validation_reports fails. Off by default so an interactive run never pages anyone; intended for a scheduled/CI invocation of this script.') ;;
    refresh_validations.py) kind='opts'; cands=(--strategies --start --end --output-dir --n-cpcv-splits --n-test-splits --json); disp=('--strategies  -- Comma-separated strategy names to validate. Default: all (coppock_momentum, cross_sectional_momentum, deep_value_edgar_pit, dividend_yield_edgar_pit, forecast_direction_arima_hw, garch_vol_target, macd_trend, macro_regime_pit, multifactor_lowvol_size, relative_strength_xsec, rsi14_extremes, rsi2_mean_reversion, signal_replay_balanced_blend, sortino_drawdown, timeseries_momentum, value_quality_edgar_pit).' '--start  -- Backtest start date (default: 2005-01-01).' '--end  -- Backtest end date (default: today).' '--output-dir  -- Directory for JSON report output (default: reports/).' '--n-cpcv-splits  -- Number of CPCV splits (default: 10).' '--n-test-splits  -- Walk-forward test splits (default: 2).' '--json  -- Also print ONE machine-readable JSON line (the LAST line of stdout) mapping strategy_id → {deployable, pbo, dsr, sharpe, max_drawdown[, error]}. The human pass/fail table is still printed above it.') ;;
    daily_briefing.py) kind='opts'; cands=(--output-dir --print); disp=('--output-dir  -- Directory containing state_snapshot.json, dead_letter.json, history/. Default: ./output' '--print  -- Also print the briefing to stdout after writing the file.') ;;
    track_record_status.py) kind='opts'; cands=(--output-dir --json); disp=('--output-dir  -- Directory containing decision_log.jsonl, heartbeat.txt, state_snapshot.json. Default: ./output' '--json  -- Emit machine-readable JSON instead of the human-readable report.') ;;
  esac

  if [[ "$kind" == "opts" ]]; then
    if [[ "$cur" == -* ]]; then
      compadd -d disp -a cands
    else
      _files
    fi
  elif [[ "$kind" == "subs" ]]; then
    compadd -d disp -a cands
  else
    _files
  fi
}
compdef _investyo_complete python python3
