# investyo command completion (bash) — GENERATED by
# scripts/generate_shell_completion.py from cli_introspect/command_manifest.json.
# Do not edit by hand; re-run the generator. Enable with:  source completions/investyo.bash
_investyo_complete() {
  local cur prevw w i cmd="" sub="" ctx kind="" cands
  cur="${COMP_WORDS[COMP_CWORD]}"
  for (( i=1; i < COMP_CWORD; i++ )); do
    w="${COMP_WORDS[i]}"
    prevw="${COMP_WORDS[i-1]}"
    if [[ -z "$cmd" ]]; then
      case "$w" in
        main.py|*/main.py) cmd='main.py' ;;
        main_orchestrator.py|*/main_orchestrator.py) cmd='main_orchestrator.py' ;;
        universe_engine.py|*/universe_engine.py) cmd='universe_engine.py' ;;
        app_shell.py|*/app_shell.py) cmd='app_shell.py' ;;
        execution.kill_switch) [[ "$prevw" == "-m" ]] && cmd='execution.kill_switch' ;;
        validation.harness) [[ "$prevw" == "-m" ]] && cmd='validation.harness' ;;
        prompt_registry) [[ "$prevw" == "-m" ]] && cmd='prompt_registry' ;;
        preflight_check.py|*/preflight_check.py) cmd='preflight_check.py' ;;
        refresh_validations.py|*/refresh_validations.py) cmd='refresh_validations.py' ;;
        daily_briefing.py|*/daily_briefing.py) cmd='daily_briefing.py' ;;
        track_record_status.py|*/track_record_status.py) cmd='track_record_status.py' ;;
      esac
    else
      case "$cmd" in
        prompt_registry)
          if [[ -z "$sub" ]]; then
            case "$w" in
            list) sub='list' ;;
            get) sub='get' ;;
            sync) sub='sync' ;;
            pin) sub='pin' ;;
            rollback) sub='rollback' ;;
            diff) sub='diff' ;;
            verify) sub='verify' ;;
            publish) sub='publish' ;;
            esac
          fi
          ;;
      esac
    fi
  done

  [[ -z "$cmd" ]] && { COMPREPLY=( $(compgen -f -- "$cur") ); return; }

  ctx="$cmd"; [[ -n "$sub" ]] && ctx="$cmd/$sub"
  cands=()
  case "$ctx" in
    main.py) kind='opts'; cands=(--interval --refresh-account --agent) ;;
    main_orchestrator.py) kind='opts'; cands=(--dry-run --strict) ;;
    universe_engine.py) kind='opts'; cands=(--date --report) ;;
    app_shell.py) kind='opts'; cands=(--interval) ;;
    execution.kill_switch) kind='opts'; cands=(--activate --deactivate --status --reason) ;;
    validation.harness) kind='opts'; cands=(--strategy --start --end) ;;
    prompt_registry) kind='subs'; cands=(list get sync pin rollback diff verify publish) ;;
    prompt_registry/list) kind='opts'; cands=() ;;
    prompt_registry/get) kind='opts'; cands=(--version -v --raw) ;;
    prompt_registry/sync) kind='opts'; cands=() ;;
    prompt_registry/pin) kind='opts'; cands=() ;;
    prompt_registry/rollback) kind='opts'; cands=() ;;
    prompt_registry/diff) kind='opts'; cands=() ;;
    prompt_registry/verify) kind='opts'; cands=() ;;
    prompt_registry/publish) kind='opts'; cands=(--version -v --author --notes) ;;
    preflight_check.py) kind='opts'; cands=(--json --skip --fire-alerts) ;;
    refresh_validations.py) kind='opts'; cands=(--strategies --start --end --output-dir --n-cpcv-splits --n-test-splits --json) ;;
    daily_briefing.py) kind='opts'; cands=(--output-dir --print) ;;
    track_record_status.py) kind='opts'; cands=(--output-dir --json) ;;
  esac

  if [[ "$kind" == "opts" ]]; then
    if [[ "$cur" == -* ]]; then
      COMPREPLY=( $(compgen -W "${cands[*]}" -- "$cur") )
    else
      COMPREPLY=( $(compgen -f -- "$cur") )
    fi
  elif [[ "$kind" == "subs" ]]; then
    COMPREPLY=( $(compgen -W "${cands[*]}" -- "$cur") )
  else
    COMPREPLY=( $(compgen -f -- "$cur") )
  fi
}
complete -F _investyo_complete python python3
