#compdef python python3
# investyo command completion (zsh) — GENERATED by
# scripts/generate_shell_completion.py from cli_introspect/command_manifest.json.
# Do not edit by hand; re-run the generator. Enable with:  source completions/investyo.zsh
_investyo_complete() {
  local cur w i cmd="" sub="" ctx kind=""
  local -a cands disp
  cur="${words[CURRENT]}"
  for (( i=2; i < CURRENT; i++ )); do
    w="${words[i]}"
    if [[ -z "$cmd" ]]; then
      local prevw="${words[i-1]}"
      case "$w" in
        main.py|*/main.py) cmd='main.py' ;;
        main_orchestrator.py|*/main_orchestrator.py) cmd='main_orchestrator.py' ;;
        universe_engine.py|*/universe_engine.py) cmd='universe_engine.py' ;;
        execution.kill_switch) [[ "$prevw" == "-m" ]] && cmd='execution.kill_switch' ;;
        validation.harness) [[ "$prevw" == "-m" ]] && cmd='validation.harness' ;;
        prompt_registry) [[ "$prevw" == "-m" ]] && cmd='prompt_registry' ;;
        preflight_check.py|*/preflight_check.py) cmd='preflight_check.py' ;;
        scripts.refresh_validations) [[ "$prevw" == "-m" ]] && cmd='scripts.refresh_validations' ;;
        daily_briefing.py|*/daily_briefing.py) cmd='daily_briefing.py' ;;
        track_record_status.py|*/track_record_status.py) cmd='track_record_status.py' ;;
        database_setup.py|*/database_setup.py) cmd='database_setup.py' ;;
        repair_price_bars_adjustment.py|*/repair_price_bars_adjustment.py) cmd='repair_price_bars_adjustment.py' ;;
        backfill_edgar_fundamentals.py|*/backfill_edgar_fundamentals.py) cmd='backfill_edgar_fundamentals.py' ;;
        backfill_news_history.py|*/backfill_news_history.py) cmd='backfill_news_history.py' ;;
        backfill_news_history_from_audit.py|*/backfill_news_history_from_audit.py) cmd='backfill_news_history_from_audit.py' ;;
        backfill_sentiment_history.py|*/backfill_sentiment_history.py) cmd='backfill_sentiment_history.py' ;;
        export_notebooklm.py|*/export_notebooklm.py) cmd='export_notebooklm.py' ;;
      esac
    else
      case "$cmd" in
        prompt_registry)
          if [[ -z "$sub" ]]; then
            case "$w" in
            list) sub='list' ;;
            get) sub='get' ;;
            sync) sub='sync' ;;
            pin) sub='pin' ;;
            rollback) sub='rollback' ;;
            diff) sub='diff' ;;
            verify) sub='verify' ;;
            publish) sub='publish' ;;
            esac
          fi
          ;;
      esac
    fi
  done

  if [[ -z "$cmd" ]]; then
    _files
    return
  fi

  ctx="$cmd"; [[ -n "$sub" ]] && ctx="$cmd/$sub"
  case "$ctx" in
    main.py) kind='opts'; cands=(--interval --refresh-account --agent); disp=('--interval  -- Refresh market data every N seconds (0 = run once and exit).' '--refresh-account  -- Force a fresh Robinhood fetch on this launch (bypasses daily cache).' '--agent  -- Run the autonomous advisory agent loop: adaptive cadence based on market hours / VIX / regime, backlog reminders for high-conviction signals the operator has not yet logged a decision for, persistent state across restarts.  Takes precedence over --interval.') ;;
    main_orchestrator.py) kind='opts'; cands=(--dry-run --strict); disp=('--dry-run  -- Log intended orders but do not submit to broker.' '--strict  -- Treat DashboardSchema validation failures as fatal (exit 1). For CI / schema-drift gating.') ;;
    universe_engine.py) kind='opts'; cands=(--date --report); disp=('--date  -- As-of date in YYYY-MM-DD format' '--report  -- Print survivorship bias report') ;;
    execution.kill_switch) kind='opts'; cands=(--activate --deactivate --activate-soft-halt --deactivate-soft-halt --status --reason); disp=('--activate  -- Activate the global kill switch.' '--deactivate  -- Deactivate the global kill switch.' '--activate-soft-halt  -- Activate soft halt (block BUYs).' '--deactivate-soft-halt  -- Deactivate soft halt.' '--status  -- Print current status.' '--reason  -- Reason text (--activate / --activate-soft-halt).') ;;
    validation.harness) kind='opts'; cands=(--strategy --strategies --start --end --ticker --workers -w --json); disp=('--strategy  -- Name of a single strategy to validate' '--strategies  -- Comma-separated OPTIONS strategy names to validate in bulk. Only names registered in validation.options_harness.STANDARD_OPTIONS_STRATEGIES are supported here -- for equity/cross-sectional strategies use `python -m scripts.refresh_validations --strategies ...` instead.' '--start  -- Start date (YYYY-MM-DD)' '--end  -- End date (YYYY-MM-DD)' '--ticker  -- Ticker for options strategy validation' '--workers  -- Number of concurrent workers for bulk (--strategies) validation (default: 1 for sequential).' '-w  -- Number of concurrent workers for bulk (--strategies) validation (default: 1 for sequential).' '--json  -- In bulk mode, also print ONE machine-readable JSON line (the LAST line of stdout) mapping strategy name -> {deployable, pbo, dsr, sharpe, max_drawdown[, error]}. The human pass/fail table is still printed above it.') ;;
    prompt_registry) kind='subs'; cands=(list get sync pin rollback diff verify publish); disp=('list  -- Table of prompt IDs with pinned / remote-latest / newest-cached versions.' 'get  -- Print a resolved prompt body.' 'sync  -- Fetch the remote manifest and pre-warm the disk cache.' 'pin  -- Pin a prompt ID to a specific version.' 'rollback  -- Roll back to the previous cached version.' 'diff  -- Unified diff between two versions of a prompt.' 'verify  -- Re-check signatures and guardrails for cached versions.' 'publish  -- Sign a file and push it to the remote store (publish credentials required).') ;;
    prompt_registry/list) kind='opts'; cands=(); disp=() ;;
    prompt_registry/get) kind='opts'; cands=(--version -v --raw); disp=('--version  -- Specific version (e.g. 1.0.0 or '\''baseline'\''). Default: full resolution chain.' '-v  -- Specific version (e.g. 1.0.0 or '\''baseline'\''). Default: full resolution chain.' '--raw  -- Suppress the header comment line — print body text only.') ;;
    prompt_registry/sync) kind='opts'; cands=(); disp=() ;;
    prompt_registry/pin) kind='opts'; cands=(); disp=() ;;
    prompt_registry/rollback) kind='opts'; cands=(); disp=() ;;
    prompt_registry/diff) kind='opts'; cands=(); disp=() ;;
    prompt_registry/verify) kind='opts'; cands=(); disp=() ;;
    prompt_registry/publish) kind='opts'; cands=(--version -v --author --notes); disp=('--version  -- Version string to publish (e.g. 1.1.0).' '-v  -- Version string to publish (e.g. 1.1.0).' '--author  -- Author identifier.' '--notes  -- Changelog note.') ;;
    preflight_check.py) kind='opts'; cands=(--json --skip --fire-alerts --validation-staleness-only); disp=('--json  -- Output machine-readable JSON array instead of a human-readable table' '--skip  -- Skip named checks (e.g. --skip heartbeat_fresh paper_trading_duration). Useful in CI where certain checks are contextually inapplicable.' '--fire-alerts  -- Dispatch a CRITICAL alert via observability.alerts.send_alert when validation_reports fails. Off by default so an interactive run never pages anyone; intended for a scheduled/CI invocation of this script.' '--validation-staleness-only  -- Run ONLY the validation_reports check (strategy backtest staleness and deployability), bypassing the ADVISORY_ONLY auto-skip that applies to the full go-live gate, and always firing an alert on FAIL (fire_alert=True). Intended for a daily scheduled cron invocation independent of the go-live gate below — strategy health is worth monitoring whether or not the platform is submitting live orders. Ignores --skip and --fire-alerts.') ;;
    scripts.refresh_validations) kind='opts'; cands=(--strategies --start --end --output-dir --n-cpcv-splits --n-test-splits --workers -w --json); disp=('--strategies  -- Comma-separated strategy names to validate. Default: all (aroon_trend, call_credit_spread, call_debit_spread, coppock_momentum, copula_stat_arb, covered_call, cross_sectional_momentum, deep_value_edgar_pit, dispersion_trading, dividend_yield_edgar_pit, earnings_crush, forecast_direction_arima_hw, gamma_scalper, garch_vol_target, lgbm_ranker, macd_trend, macro_regime_pit, multifactor_lowvol_size, options_flow_sentiment, pairs_trading, put_credit_spread, put_debit_spread, relative_strength_xsec, rsi14_extremes, rsi2_mean_reversion, sector_quality_rank, signal_replay_balanced_blend, sortino_drawdown, timeseries_momentum, value_quality_edgar_pit, vol_mispricing, vrp_premium_selling, zero_dte_engine).' '--start  -- Backtest start date (default: 2005-01-01).' '--end  -- Backtest end date (default: today).' '--output-dir  -- Directory for JSON report output (default: reports/).' '--n-cpcv-splits  -- Number of CPCV splits (default: 10).' '--n-test-splits  -- Walk-forward test splits (default: 2).' '--workers  -- Number of concurrent workers for strategy validation (default: 1 for sequential). See run_validations()'\''s docstring for the profiled lgbm_ranker/LightGBM thread-oversubscription caveat (measured negligible on a 10-core machine as of 2026-08-14).' '-w  -- Number of concurrent workers for strategy validation (default: 1 for sequential). See run_validations()'\''s docstring for the profiled lgbm_ranker/LightGBM thread-oversubscription caveat (measured negligible on a 10-core machine as of 2026-08-14).' '--json  -- Also print ONE machine-readable JSON line (the LAST line of stdout) mapping strategy_id → {deployable, pbo, dsr, sharpe, max_drawdown, universe_coverage_pct, universe_coverage_ok[, error]}. The human pass/fail table is still printed above it.') ;;
    daily_briefing.py) kind='opts'; cands=(--output-dir --print); disp=('--output-dir  -- Directory containing state_snapshot.json, dead_letter.json, history/. Default: ./output' '--print  -- Also print the briefing to stdout after writing the file.') ;;
    track_record_status.py) kind='opts'; cands=(--output-dir --json); disp=('--output-dir  -- Directory containing decision_log.jsonl, heartbeat.txt, state_snapshot.json. Default: ./output' '--json  -- Emit machine-readable JSON instead of the human-readable report.') ;;
    database_setup.py) kind='opts'; cands=(); disp=() ;;
    repair_price_bars_adjustment.py) kind='opts'; cands=(--tickers --random --source --dry-run); disp=('--tickers  -- Comma-separated ticker list (e.g. '\''AAPL,MSFT'\''), '\''universe'\'' for the operator'\''s tracked universe (held ∪ watchlists ∪ DEFAULT_TICKERS, via resolve_universe), or '\''all'\'' for every symbol currently carrying a --source row in price_bars.' '--random  -- Add this many additional random symbols (from every symbol carrying a --source row in price_bars) on top of --tickers. Skips symbols already selected.' '--source  -- price_bars.source value that identifies the affected rows (default: '\''fmpprovider'\'').' '--dry-run  -- Report what would be deleted/re-fetched per symbol without touching the DB.') ;;
    backfill_edgar_fundamentals.py) kind='opts'; cands=(--tickers --since); disp=('--tickers  -- Comma separated list of tickers, or '\''all'\'' for the operator'\''s tracked universe (held ∪ watchlists ∪ DEFAULT_TICKERS).' '--since  -- YYYY-MM-DD cutoff') ;;
    backfill_news_history.py) kind='opts'; cands=(--tickers --months); disp=('--tickers  -- Comma-separated tickers, or '\''all'\'' for the operator'\''s tracked universe (held ∪ watchlists ∪ DEFAULT_TICKERS).' '--months  -- How many months back to backfill (default: 6). See module docstring: with FMP as the provider this covers real history (verified live 2026-08: >=6 months); Finnhub'\''s free tier only has ~3 months, with the remainder archiving as honest NaN gaps.') ;;
    backfill_news_history_from_audit.py) kind='opts'; cands=(--tickers --months); disp=('--tickers  -- Comma-separated tickers, or '\''all'\'' for the operator'\''s tracked universe (held ∪ watchlists ∪ DEFAULT_TICKERS).' '--months  -- How many months back to aggregate (default: 6). Only days already covered by sentiment_ingestion_audit (see scripts/backfill_sentiment_history.py) produce a real value; the rest archive as honest NaN gaps.') ;;
    backfill_sentiment_history.py) kind='opts'; cands=(--tickers --months --sources --max-seconds-per-symbol); disp=('--tickers  -- Comma-separated tickers, or '\''all'\'' for the operator'\''s tracked universe (held ∪ watchlists ∪ DEFAULT_TICKERS).' '--months  -- How many months back to backfill (default: 5).' '--sources  -- Comma-separated source names to backfill (default excludes yahoo_rss -- it has no historical archive; see module docstring).' '--max-seconds-per-symbol  -- Wall-clock budget per symbol for this run, overriding settings.SENTIMENT_INGESTION_MAX_SECONDS_PER_CYCLE (whose 60s default is sized for a live per-cycle refresh, not a real multi-month historical backfill).') ;;
    export_notebooklm.py) kind='opts'; cands=(--output-dir --modular-only --consolidated-only --section); disp=('--output-dir  -- Override the output directory (defaults to settings.OUTPUT_DIR).' '--modular-only  -- Only generate the 5 modular notebooklm/0N_*.md files; skip the consolidated export.' '--consolidated-only  -- Only generate the consolidated notebooklm_source.md; skip the 5 modular files.' '--section  -- Generate only this one modular section (implies --modular-only for that section).') ;;
  esac

  if [[ "$kind" == "opts" ]]; then
    if [[ "$cur" == -* ]]; then
      compadd -d disp -a cands
    else
      _files
    fi
  elif [[ "$kind" == "subs" ]]; then
    compadd -d disp -a cands
  else
    _files
  fi
}
compdef _investyo_complete python python3
