import json
from typing import Dict, Any
from langchain_core.language_models.chat_models import BaseChatModel
from langchain_core.messages import SystemMessage, HumanMessage

# Assuming existence of the risk gate mentioned in the spec
# from execution.risk_gate import PreTradeRiskGate

def run_execution(research_data: Dict[str, Any], llm: BaseChatModel) -> Dict[str, Any]:
    """
    Agent 2 (Strategy/Execution): Uses high-reasoning LLM to deduce sizing 
    and strategy based on research, strictly gated by advisory parameters.
    
    Args:
        research_data (Dict[str, Any]): The payload generated by run_research.
        llm (BaseChatModel): The LangChain high-reasoning chat model.
        
    Returns:
        Dict[str, Any]: The finalized, risk-gated execution/advisory plan.
    """
    
    # Safety Hardcode
    ADVISORY_ONLY = True
    
    system_prompt = (
        "You are an automated execution strategist. Based on the synthesized research provided, "
        "formulate an execution plan. You must apply standard quantitative principles (e.g., "
        "volatility targeting, Kelly criterion approximations) to suggest theoretical sizing. "
        "Since ADVISORY_ONLY is active, you must format your output as a theoretical strategy, not a live trade command. "
        "Return your analysis in valid JSON format containing: 'rationale', 'suggested_allocations' (by ticker), and 'risk_warnings'."
    )
    
    human_prompt = f"""
    Research Synthesis: 
    {research_data['llm_synthesis']}
    
    Original Query: {research_data['original_query']}
    
    Generate the JSON execution plan.
    """
    
    messages = [
        SystemMessage(content=system_prompt),
        HumanMessage(content=human_prompt)
    ]
    
    # Enforce JSON output for the execution plan
    response = llm.invoke(messages)
    
    try:
        # Strip potential markdown code blocks if the LLM adds them
        clean_json = response.content.replace("```json", "").replace("```", "").strip()
        execution_plan = json.loads(clean_json)
    except json.JSONDecodeError:
        # Fallback if the LLM fails to return strict JSON
        execution_plan = {
            "rationale": "Failed to parse structured strategy from LLM.",
            "suggested_allocations": {},
            "risk_warnings": [response.content]
        }

    # Format the draft response
    draft_response = {
        "advisory_only": ADVISORY_ONLY,
        "research_context": research_data['llm_synthesis'],
        "execution_plan": execution_plan
    }
    
    return draft_response
